/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Container: typeof import('./../src/components/Container/src/Container.vue')['default']
    ImageSwiper: typeof import('./../src/components/Swiper/src/ImageSwiper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Swiper: typeof import('./../src/components/Swiper/src/Swiper.vue')['default']
  }
}
